CREATE TABLE postgres_ch_db.mock_data_temp
(
    id String,
    customer_first_name String,
    customer_last_name String,
    customer_age String,
    customer_email String,
    customer_country String,
    customer_postal_code String,
    customer_pet_type String,
    customer_pet_name String,
    customer_pet_breed String,
    seller_first_name String,
    seller_last_name String,
    seller_email String,
    seller_country String,
    seller_postal_code String,
    product_name String,
    product_category String,
    product_price String,
    product_quantity String,
    sale_date String,
    sale_customer_id String,
    sale_seller_id String,
    sale_product_id String,
    sale_quantity String,
    sale_total_price String,
    store_name String,
    store_location String,
    store_city String,
    store_state String,
    store_country String,
    store_phone String,
    store_email String,
    pet_category String,
    product_weight String,
    product_color String,
    product_size String,
    product_brand String,
    product_material String,
    product_description String,
    product_rating String,
    product_reviews String,
    product_release_date String,
    product_expiry_date String,
    supplier_name String,
    supplier_contact String,
    supplier_email String,
    supplier_phone String,
    supplier_address String,
    supplier_city String,
    supplier_country String
)
ENGINE = MergeTree()
ORDER BY (id);
INSERT INTO postgres_ch_db.mock_data_temp FROM INFILE '/tmp/data/MOCK_DATA (5).csv' FORMAT CSVWithNames;
INSERT INTO postgres_ch_db.mock_data_temp FROM INFILE '/tmp/data/MOCK_DATA (6).csv' FORMAT CSVWithNames;
INSERT INTO postgres_ch_db.mock_data_temp FROM INFILE '/tmp/data/MOCK_DATA (7).csv' FORMAT CSVWithNames;
INSERT INTO postgres_ch_db.mock_data_temp FROM INFILE '/tmp/data/MOCK_DATA (8).csv' FORMAT CSVWithNames;
INSERT INTO postgres_ch_db.mock_data_temp FROM INFILE '/tmp/data/MOCK_DATA (9).csv' FORMAT CSVWithNames;

CREATE TABLE postgres_ch_db.mock_data
(
    id UInt32,
    customer_first_name String,
    customer_last_name String,
    customer_age UInt8,
    customer_email String,
    customer_country String,
    customer_postal_code String,
    customer_pet_type String,
    customer_pet_name String,
    customer_pet_breed String,
    seller_first_name String,
    seller_last_name String,
    seller_email String,
    seller_country String,
    seller_postal_code String,
    product_name String,
    product_category String,
    product_price Decimal64(2),
    product_quantity UInt32,
    sale_date Date,
    sale_customer_id UInt32,
    sale_seller_id UInt32,
    sale_product_id UInt32,
    sale_quantity UInt32,
    sale_total_price Decimal64(2),
    store_name String,
    store_location String,
    store_city String,
    store_state String,
    store_country String,
    store_phone String,
    store_email String,
    pet_category String,
    product_weight Decimal64(2),
    product_color String,
    product_size String,
    product_brand String,
    product_material String,
    product_description String,
    product_rating Decimal32(1),
    product_reviews UInt32,
    product_release_date Date,
    product_expiry_date Date,
    supplier_name String,
    supplier_contact String,
    supplier_email String,
    supplier_phone String,
    supplier_address String,
    supplier_city String,
    supplier_country String
)
ENGINE = MergeTree()
ORDER BY (sale_date, id);

INSERT INTO postgres_ch_db.mock_data
SELECT
    cast(id as UInt32) as id,
    customer_first_name,
    customer_last_name,
    cast(customer_age as UInt8) as customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    cast(product_price as Decimal64(2)) as product_price,
    cast(product_quantity as UInt32) as product_quantity,
    parseDateTimeBestEffort(sale_date) as sale_date,
    cast(sale_customer_id as UInt32) as sale_customer_id,
    cast(sale_seller_id as UInt32) as sale_seller_id,
    cast(sale_product_id as UInt32) as sale_product_id,
    cast(sale_quantity as UInt32) as sale_quantity,
    cast(sale_total_price as Decimal64(2)) as sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    cast(product_weight as Decimal64(2)) as product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    cast(product_rating as Decimal32(1)) as product_rating,
    cast(product_reviews as UInt32) as product_reviews,
    parseDateTimeBestEffort(product_release_date) as product_release_date,
    parseDateTimeBestEffort(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM postgres_ch_db.mock_data_temp;

DROP TABLE postgres_ch_db.mock_data_temp;